### ISSUE TITLE
API issue

### ISSUE THREAD

**Issue by ruthalivingstone** [7thcirclegit/mainwp-broken-links-checker-extension#1]
![image](https://user-images.githubusercontent.com/81622485/178308877-e320b992-802c-401a-a9e2-928b772a4ca8.png)
I have installed this extension with help from this forum: https://managers.mainwp.com/t/bring-back-broken-link-checker/2036/11

The API box is showing an error message "We are unable to find an order for this Extension - Contact MainWP Support" when it is empty. When it is filled with a valid API key the error message changes to: "A customer account does not exist for this API Key." This is a lifetime key that works for everything else. 

The extension is working to an extent, the dashboard and settings tabs work, but the links tab doesn't. I tried rolling back to version 4.0.0.3 (before the nonce edit), but it didn't make any difference.

I'm happy to help work on this plugin, but would appreciate some pointers.

**Comment by ruthalivingstone** [comment]
By the way - thanks so much 7thcircle for all your work! I can't understand why mainWP aren't putting their own resources into this

**Comment by 7thcirclegit** [comment]
> ![image](https://user-images.githubusercontent.com/81622485/178308877-e320b992-802c-401a-a9e2-928b772a4ca8.png) I have installed this extension with help from this forum: https://managers.mainwp.com/t/bring-back-broken-link-checker/2036/11
> 
> The API box is showing an error message "We are unable to find an order for this Extension - Contact MainWP Support" when it is empty. When it is filled with a valid API key the error message changes to: "A customer account does not exist for this API Key." This is a lifetime key that works for everything else.
> 
> The extension is working to an extent, the dashboard and settings tabs work, but the links tab doesn't. I tried rolling back to version 4.0.0.3 (before the nonce edit), but it didn't make any difference.
> 
> I'm happy to help work on this plugin, but would appreciate some pointers.

The license key is not required anymore since they no longer support it. The key is only needed to get updates from them.

There are several items that don't work, and have not in some time. I have maintained the ability to collect counts so I know what sites have issues, but the ability to fix the links on the dashboard has never been great due to the plugin on the child sites.

MainWP will probably never bring this plugin back since the child version is owned by ManageWP

**Comment by ruthalivingstone** [comment]
Thanks for your response. Even without the links tab it's a great addition for my clients. Thanks again for your work.

Perhaps one day MainWP will make their own version. We can but hope
